### ISSUE TITLE
Problem compiling

### ISSUE THREAD

**Issue by alecazam** [MREdigital/MTKView_visionOS#1]
I think you're using a class that isn't included.

```
line 188:
public func updateViewSizeBuffer() {
        let scale = Screen.scale <-
     
workaround
       //let scale = Screen.scale
       let drawableSize = bounds.size //  * scale

MTKView_visionOS.swift:188:21 Cannot find 'Screen' in scope
```

This is cool that you wrote this.  Nice way to get 2d content up and running again.  I'm just not sure that I want multiple CADisplayLink running, but maybe it's unavoidable.   And the drawable pool is a bit complex (f.e. framebufferOnly).   There is also a new CAMetalDisplayLink, but that may not have visionOS support.

**Comment by MrEdigital** [comment]
Hey, thanks for the comment, Alec!

I added the Screen alias I use to the repo as an optional import to resolve your issue.  If only being used on visionOS, `Screen.scale` is only ever 1, and can be simplified further.

I'll have to check out CAMetalDisplayLink, to see if it provides any benefit when revisiting this again in the future.  Not something I was aware of at the time.  Thanks again!
